###################################################################

# Created by write_sdc on Mon Aug 31 00:23:04 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports in_valid]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[31\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[30\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[29\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[28\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[27\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[26\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[25\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[24\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[23\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[22\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[21\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[20\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[19\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[18\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[17\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[16\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[15\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[14\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[13\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[12\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[11\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[10\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[9\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[8\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[7\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[6\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[5\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[4\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[3\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[2\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[1\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {x\\\\[0\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[31\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[30\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[29\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[28\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[27\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[26\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[25\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[24\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[23\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[22\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[21\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[20\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[19\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[18\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[17\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[16\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[15\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[14\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[13\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[12\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[11\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[10\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[9\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[8\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[7\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[6\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[5\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[4\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[3\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[2\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[1\\\\]}]
set_load -pin_load 0.005 [get_ports {y\\\\[0\\\\]}]
set_load -pin_load 0.005 [get_ports out_valid]
create_clock [get_ports clk]  -period 699  -waveform {0 349.5}
set_clock_uncertainty 50  [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports in_valid]
set_input_delay -clock clk  0  [get_ports {x\\\\[31\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[30\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[29\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[28\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[27\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[26\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[25\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[24\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[23\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[22\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[21\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[20\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[19\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[18\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[17\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[16\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[15\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[14\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[13\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[12\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[11\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[10\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[9\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[8\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[7\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[6\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[5\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[4\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[3\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[2\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[1\\\\]}]
set_input_delay -clock clk  0  [get_ports {x\\\\[0\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[31\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[30\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[29\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[28\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[27\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[26\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[25\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[24\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[23\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[22\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[21\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[20\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[19\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[18\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[17\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[16\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[15\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[14\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[13\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[12\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[11\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[10\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[9\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[8\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[7\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[6\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[5\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[4\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[3\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[2\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[1\\\\]}]
set_output_delay -clock clk  0  [get_ports {y\\\\[0\\\\]}]
set_output_delay -clock clk  0  [get_ports out_valid]
