// sincos_bf16.sv — BF16 sine/cosine generator (LUT + linear interpolation).
// GENERATED by scratchpad/gen_sincos.py — do not hand-edit the LUT.
//
// Input `phase` is an unsigned 16-bit angle in units of turns: the full circle
// [0, 2*pi) maps to [0, 65536). A 256-entry BF16 sine table is indexed by the
// top 8 bits and linearly interpolated with the low 8 bits; cos is the same
// table read at phase + quarter-turn (sin(x + pi/2)). Interpolation reuses the
// bf16_add / bf16_mult primitives, so latency = 3 cycles (registered, valid-piped).
//
//   sin = s0 + (s1 - s0) * frac ,  frac = phase[7:0]/256
//   cos = c0 + (c1 - c0) * frac ,  read at phase + 16384
module sincos_bf16 (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        in_valid,
    input  logic [15:0] phase,      // [0,2*pi) -> [0,65536)
    output logic [15:0] sin_bf16,
    output logic [15:0] cos_bf16,
    output logic        out_valid
);
    // ---- 256-entry BF16 sine table: sin(2*pi*idx/256) ----
    function automatic logic [15:0] sin_lut(input logic [7:0] idx);
        begin
            unique case (idx)
                8'd0: sin_lut = 16'h0000;
                8'd1: sin_lut = 16'h3CC9;
                8'd2: sin_lut = 16'h3D49;
                8'd3: sin_lut = 16'h3D97;
                8'd4: sin_lut = 16'h3DC9;
                8'd5: sin_lut = 16'h3DFB;
                8'd6: sin_lut = 16'h3E16;
                8'd7: sin_lut = 16'h3E2F;
                8'd8: sin_lut = 16'h3E48;
                8'd9: sin_lut = 16'h3E60;
                8'd10: sin_lut = 16'h3E79;
                8'd11: sin_lut = 16'h3E89;
                8'd12: sin_lut = 16'h3E95;
                8'd13: sin_lut = 16'h3EA1;
                8'd14: sin_lut = 16'h3EAC;
                8'd15: sin_lut = 16'h3EB8;
                8'd16: sin_lut = 16'h3EC4;
                8'd17: sin_lut = 16'h3ECF;
                8'd18: sin_lut = 16'h3EDB;
                8'd19: sin_lut = 16'h3EE6;
                8'd20: sin_lut = 16'h3EF1;
                8'd21: sin_lut = 16'h3EFC;
                8'd22: sin_lut = 16'h3F04;
                8'd23: sin_lut = 16'h3F09;
                8'd24: sin_lut = 16'h3F0E;
                8'd25: sin_lut = 16'h3F13;
                8'd26: sin_lut = 16'h3F18;
                8'd27: sin_lut = 16'h3F1D;
                8'd28: sin_lut = 16'h3F22;
                8'd29: sin_lut = 16'h3F27;
                8'd30: sin_lut = 16'h3F2C;
                8'd31: sin_lut = 16'h3F31;
                8'd32: sin_lut = 16'h3F35;
                8'd33: sin_lut = 16'h3F39;
                8'd34: sin_lut = 16'h3F3E;
                8'd35: sin_lut = 16'h3F42;
                8'd36: sin_lut = 16'h3F46;
                8'd37: sin_lut = 16'h3F4A;
                8'd38: sin_lut = 16'h3F4E;
                8'd39: sin_lut = 16'h3F51;
                8'd40: sin_lut = 16'h3F55;
                8'd41: sin_lut = 16'h3F58;
                8'd42: sin_lut = 16'h3F5C;
                8'd43: sin_lut = 16'h3F5F;
                8'd44: sin_lut = 16'h3F62;
                8'd45: sin_lut = 16'h3F65;
                8'd46: sin_lut = 16'h3F67;
                8'd47: sin_lut = 16'h3F6A;
                8'd48: sin_lut = 16'h3F6D;
                8'd49: sin_lut = 16'h3F6F;
                8'd50: sin_lut = 16'h3F71;
                8'd51: sin_lut = 16'h3F73;
                8'd52: sin_lut = 16'h3F75;
                8'd53: sin_lut = 16'h3F77;
                8'd54: sin_lut = 16'h3F78;
                8'd55: sin_lut = 16'h3F7A;
                8'd56: sin_lut = 16'h3F7B;
                8'd57: sin_lut = 16'h3F7C;
                8'd58: sin_lut = 16'h3F7D;
                8'd59: sin_lut = 16'h3F7E;
                8'd60: sin_lut = 16'h3F7F;
                8'd61: sin_lut = 16'h3F7F;
                8'd62: sin_lut = 16'h3F80;
                8'd63: sin_lut = 16'h3F80;
                8'd64: sin_lut = 16'h3F80;
                8'd65: sin_lut = 16'h3F80;
                8'd66: sin_lut = 16'h3F80;
                8'd67: sin_lut = 16'h3F7F;
                8'd68: sin_lut = 16'h3F7F;
                8'd69: sin_lut = 16'h3F7E;
                8'd70: sin_lut = 16'h3F7D;
                8'd71: sin_lut = 16'h3F7C;
                8'd72: sin_lut = 16'h3F7B;
                8'd73: sin_lut = 16'h3F7A;
                8'd74: sin_lut = 16'h3F78;
                8'd75: sin_lut = 16'h3F77;
                8'd76: sin_lut = 16'h3F75;
                8'd77: sin_lut = 16'h3F73;
                8'd78: sin_lut = 16'h3F71;
                8'd79: sin_lut = 16'h3F6F;
                8'd80: sin_lut = 16'h3F6D;
                8'd81: sin_lut = 16'h3F6A;
                8'd82: sin_lut = 16'h3F67;
                8'd83: sin_lut = 16'h3F65;
                8'd84: sin_lut = 16'h3F62;
                8'd85: sin_lut = 16'h3F5F;
                8'd86: sin_lut = 16'h3F5C;
                8'd87: sin_lut = 16'h3F58;
                8'd88: sin_lut = 16'h3F55;
                8'd89: sin_lut = 16'h3F51;
                8'd90: sin_lut = 16'h3F4E;
                8'd91: sin_lut = 16'h3F4A;
                8'd92: sin_lut = 16'h3F46;
                8'd93: sin_lut = 16'h3F42;
                8'd94: sin_lut = 16'h3F3E;
                8'd95: sin_lut = 16'h3F39;
                8'd96: sin_lut = 16'h3F35;
                8'd97: sin_lut = 16'h3F31;
                8'd98: sin_lut = 16'h3F2C;
                8'd99: sin_lut = 16'h3F27;
                8'd100: sin_lut = 16'h3F22;
                8'd101: sin_lut = 16'h3F1D;
                8'd102: sin_lut = 16'h3F18;
                8'd103: sin_lut = 16'h3F13;
                8'd104: sin_lut = 16'h3F0E;
                8'd105: sin_lut = 16'h3F09;
                8'd106: sin_lut = 16'h3F04;
                8'd107: sin_lut = 16'h3EFC;
                8'd108: sin_lut = 16'h3EF1;
                8'd109: sin_lut = 16'h3EE6;
                8'd110: sin_lut = 16'h3EDB;
                8'd111: sin_lut = 16'h3ECF;
                8'd112: sin_lut = 16'h3EC4;
                8'd113: sin_lut = 16'h3EB8;
                8'd114: sin_lut = 16'h3EAC;
                8'd115: sin_lut = 16'h3EA1;
                8'd116: sin_lut = 16'h3E95;
                8'd117: sin_lut = 16'h3E89;
                8'd118: sin_lut = 16'h3E79;
                8'd119: sin_lut = 16'h3E60;
                8'd120: sin_lut = 16'h3E48;
                8'd121: sin_lut = 16'h3E2F;
                8'd122: sin_lut = 16'h3E16;
                8'd123: sin_lut = 16'h3DFB;
                8'd124: sin_lut = 16'h3DC9;
                8'd125: sin_lut = 16'h3D97;
                8'd126: sin_lut = 16'h3D49;
                8'd127: sin_lut = 16'h3CC9;
                8'd128: sin_lut = 16'h250D;
                8'd129: sin_lut = 16'hBCC9;
                8'd130: sin_lut = 16'hBD49;
                8'd131: sin_lut = 16'hBD97;
                8'd132: sin_lut = 16'hBDC9;
                8'd133: sin_lut = 16'hBDFB;
                8'd134: sin_lut = 16'hBE16;
                8'd135: sin_lut = 16'hBE2F;
                8'd136: sin_lut = 16'hBE48;
                8'd137: sin_lut = 16'hBE60;
                8'd138: sin_lut = 16'hBE79;
                8'd139: sin_lut = 16'hBE89;
                8'd140: sin_lut = 16'hBE95;
                8'd141: sin_lut = 16'hBEA1;
                8'd142: sin_lut = 16'hBEAC;
                8'd143: sin_lut = 16'hBEB8;
                8'd144: sin_lut = 16'hBEC4;
                8'd145: sin_lut = 16'hBECF;
                8'd146: sin_lut = 16'hBEDB;
                8'd147: sin_lut = 16'hBEE6;
                8'd148: sin_lut = 16'hBEF1;
                8'd149: sin_lut = 16'hBEFC;
                8'd150: sin_lut = 16'hBF04;
                8'd151: sin_lut = 16'hBF09;
                8'd152: sin_lut = 16'hBF0E;
                8'd153: sin_lut = 16'hBF13;
                8'd154: sin_lut = 16'hBF18;
                8'd155: sin_lut = 16'hBF1D;
                8'd156: sin_lut = 16'hBF22;
                8'd157: sin_lut = 16'hBF27;
                8'd158: sin_lut = 16'hBF2C;
                8'd159: sin_lut = 16'hBF31;
                8'd160: sin_lut = 16'hBF35;
                8'd161: sin_lut = 16'hBF39;
                8'd162: sin_lut = 16'hBF3E;
                8'd163: sin_lut = 16'hBF42;
                8'd164: sin_lut = 16'hBF46;
                8'd165: sin_lut = 16'hBF4A;
                8'd166: sin_lut = 16'hBF4E;
                8'd167: sin_lut = 16'hBF51;
                8'd168: sin_lut = 16'hBF55;
                8'd169: sin_lut = 16'hBF58;
                8'd170: sin_lut = 16'hBF5C;
                8'd171: sin_lut = 16'hBF5F;
                8'd172: sin_lut = 16'hBF62;
                8'd173: sin_lut = 16'hBF65;
                8'd174: sin_lut = 16'hBF67;
                8'd175: sin_lut = 16'hBF6A;
                8'd176: sin_lut = 16'hBF6D;
                8'd177: sin_lut = 16'hBF6F;
                8'd178: sin_lut = 16'hBF71;
                8'd179: sin_lut = 16'hBF73;
                8'd180: sin_lut = 16'hBF75;
                8'd181: sin_lut = 16'hBF77;
                8'd182: sin_lut = 16'hBF78;
                8'd183: sin_lut = 16'hBF7A;
                8'd184: sin_lut = 16'hBF7B;
                8'd185: sin_lut = 16'hBF7C;
                8'd186: sin_lut = 16'hBF7D;
                8'd187: sin_lut = 16'hBF7E;
                8'd188: sin_lut = 16'hBF7F;
                8'd189: sin_lut = 16'hBF7F;
                8'd190: sin_lut = 16'hBF80;
                8'd191: sin_lut = 16'hBF80;
                8'd192: sin_lut = 16'hBF80;
                8'd193: sin_lut = 16'hBF80;
                8'd194: sin_lut = 16'hBF80;
                8'd195: sin_lut = 16'hBF7F;
                8'd196: sin_lut = 16'hBF7F;
                8'd197: sin_lut = 16'hBF7E;
                8'd198: sin_lut = 16'hBF7D;
                8'd199: sin_lut = 16'hBF7C;
                8'd200: sin_lut = 16'hBF7B;
                8'd201: sin_lut = 16'hBF7A;
                8'd202: sin_lut = 16'hBF78;
                8'd203: sin_lut = 16'hBF77;
                8'd204: sin_lut = 16'hBF75;
                8'd205: sin_lut = 16'hBF73;
                8'd206: sin_lut = 16'hBF71;
                8'd207: sin_lut = 16'hBF6F;
                8'd208: sin_lut = 16'hBF6D;
                8'd209: sin_lut = 16'hBF6A;
                8'd210: sin_lut = 16'hBF67;
                8'd211: sin_lut = 16'hBF65;
                8'd212: sin_lut = 16'hBF62;
                8'd213: sin_lut = 16'hBF5F;
                8'd214: sin_lut = 16'hBF5C;
                8'd215: sin_lut = 16'hBF58;
                8'd216: sin_lut = 16'hBF55;
                8'd217: sin_lut = 16'hBF51;
                8'd218: sin_lut = 16'hBF4E;
                8'd219: sin_lut = 16'hBF4A;
                8'd220: sin_lut = 16'hBF46;
                8'd221: sin_lut = 16'hBF42;
                8'd222: sin_lut = 16'hBF3E;
                8'd223: sin_lut = 16'hBF39;
                8'd224: sin_lut = 16'hBF35;
                8'd225: sin_lut = 16'hBF31;
                8'd226: sin_lut = 16'hBF2C;
                8'd227: sin_lut = 16'hBF27;
                8'd228: sin_lut = 16'hBF22;
                8'd229: sin_lut = 16'hBF1D;
                8'd230: sin_lut = 16'hBF18;
                8'd231: sin_lut = 16'hBF13;
                8'd232: sin_lut = 16'hBF0E;
                8'd233: sin_lut = 16'hBF09;
                8'd234: sin_lut = 16'hBF04;
                8'd235: sin_lut = 16'hBEFC;
                8'd236: sin_lut = 16'hBEF1;
                8'd237: sin_lut = 16'hBEE6;
                8'd238: sin_lut = 16'hBEDB;
                8'd239: sin_lut = 16'hBECF;
                8'd240: sin_lut = 16'hBEC4;
                8'd241: sin_lut = 16'hBEB8;
                8'd242: sin_lut = 16'hBEAC;
                8'd243: sin_lut = 16'hBEA1;
                8'd244: sin_lut = 16'hBE95;
                8'd245: sin_lut = 16'hBE89;
                8'd246: sin_lut = 16'hBE79;
                8'd247: sin_lut = 16'hBE60;
                8'd248: sin_lut = 16'hBE48;
                8'd249: sin_lut = 16'hBE2F;
                8'd250: sin_lut = 16'hBE16;
                8'd251: sin_lut = 16'hBDFB;
                8'd252: sin_lut = 16'hBDC9;
                8'd253: sin_lut = 16'hBD97;
                8'd254: sin_lut = 16'hBD49;
                8'd255: sin_lut = 16'hBCC9;
                default: sin_lut = 16'h0000;
            endcase
        end
    endfunction

    // ---- unsigned 8-bit fraction (u/256) -> BF16 in [0,1) ----
    function automatic logic [15:0] u8_to_bf16(input logic [7:0] u);
        logic [3:0] k;
        logic [7:0] norm;
        logic [7:0] exp_b;
        begin
            if (u == 8'd0) u8_to_bf16 = 16'd0;
            else begin
                casez (u)
                    8'b1???????: k = 4'd7;
                    8'b01??????: k = 4'd6;
                    8'b001?????: k = 4'd5;
                    8'b0001????: k = 4'd4;
                    8'b00001???: k = 4'd3;
                    8'b000001??: k = 4'd2;
                    8'b0000001?: k = 4'd1;
                    default:     k = 4'd0;   // 8'b00000001
                endcase
                norm  = u << (4'd7 - k);       // leading 1 -> bit7
                exp_b = {4'd0, k} + 8'd119;    // bias 127, value * 2^-8
                u8_to_bf16 = {1'b0, exp_b, norm[6:0]};
            end
        end
    endfunction

    // ================= combinational LUT + fraction (t0) =================
    wire [7:0]  si   = phase[15:8];
    wire [7:0]  sfr  = phase[7:0];
    wire [15:0] pcos = phase + 16'd16384;      // + quarter turn
    wire [7:0]  ci   = pcos[15:8];
    wire [7:0]  cfr  = pcos[7:0];

    wire [15:0] s0 = sin_lut(si);
    wire [15:0] s1 = sin_lut(si + 8'd1);
    wire [15:0] c0 = sin_lut(ci);
    wire [15:0] c1 = sin_lut(ci + 8'd1);
    wire [15:0] s0_neg = {~s0[15], s0[14:0]};
    wire [15:0] c0_neg = {~c0[15], c0[14:0]};
    wire [15:0] sfrac  = u8_to_bf16(sfr);
    wire [15:0] cfrac  = u8_to_bf16(cfr);

    // ================= interpolation pipeline (3 bf16 stages) ============
    // stage A: diff = s1 - s0   (t0 -> t1)
    logic [15:0] s_diff, c_diff;  logic diffv;
    bf16_add u_sdiff (.clk(clk),.rst_n(rst_n),.in_valid(in_valid),.a(s1),.b(s0_neg),.y(s_diff),.out_valid(diffv));
    bf16_add u_cdiff (.clk(clk),.rst_n(rst_n),.in_valid(in_valid),.a(c1),.b(c0_neg),.y(c_diff),.out_valid());

    // operands that must survive to later stages
    logic [15:0] sfrac_d1, cfrac_d1;          // needed at stage B (t1)
    logic [15:0] s0_d1, s0_d2, c0_d1, c0_d2;  // needed at stage C (t2)
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sfrac_d1<='0; cfrac_d1<='0; s0_d1<='0; s0_d2<='0; c0_d1<='0; c0_d2<='0;
        end else begin
            sfrac_d1<=sfrac; cfrac_d1<=cfrac;
            s0_d1<=s0; s0_d2<=s0_d1;
            c0_d1<=c0; c0_d2<=c0_d1;
        end
    end

    // stage B: term = diff * frac  (t1 -> t2)
    logic [15:0] s_term, c_term;  logic termv;
    bf16_mult u_sterm (.clk(clk),.rst_n(rst_n),.in_valid(diffv),.a(s_diff),.b(sfrac_d1),.y(s_term),.out_valid(termv));
    bf16_mult u_cterm (.clk(clk),.rst_n(rst_n),.in_valid(diffv),.a(c_diff),.b(cfrac_d1),.y(c_term),.out_valid());

    // stage C: val = s0 + term  (t2 -> t3)
    bf16_add u_sval (.clk(clk),.rst_n(rst_n),.in_valid(termv),.a(s0_d2),.b(s_term),.y(sin_bf16),.out_valid(out_valid));
    bf16_add u_cval (.clk(clk),.rst_n(rst_n),.in_valid(termv),.a(c0_d2),.b(c_term),.y(cos_bf16),.out_valid());
endmodule
