###################################################################

# Created by write_sdc on Tue Sep  1 00:20:05 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports wr_en]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_addr[0]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[15]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[14]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[13]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[12]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[11]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[10]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[9]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[8]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[7]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[6]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {wr_data[0]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports rd_en]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {rd_addr[0]}]
set_load -pin_load 0.005 [get_ports {rd_data[15]}]
set_load -pin_load 0.005 [get_ports {rd_data[14]}]
set_load -pin_load 0.005 [get_ports {rd_data[13]}]
set_load -pin_load 0.005 [get_ports {rd_data[12]}]
set_load -pin_load 0.005 [get_ports {rd_data[11]}]
set_load -pin_load 0.005 [get_ports {rd_data[10]}]
set_load -pin_load 0.005 [get_ports {rd_data[9]}]
set_load -pin_load 0.005 [get_ports {rd_data[8]}]
set_load -pin_load 0.005 [get_ports {rd_data[7]}]
set_load -pin_load 0.005 [get_ports {rd_data[6]}]
set_load -pin_load 0.005 [get_ports {rd_data[5]}]
set_load -pin_load 0.005 [get_ports {rd_data[4]}]
set_load -pin_load 0.005 [get_ports {rd_data[3]}]
set_load -pin_load 0.005 [get_ports {rd_data[2]}]
set_load -pin_load 0.005 [get_ports {rd_data[1]}]
set_load -pin_load 0.005 [get_ports {rd_data[0]}]
create_clock [get_ports clk]  -period 769  -waveform {0 384.5}
set_clock_uncertainty 50  [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  230.7  [get_ports wr_en]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[5]}]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[4]}]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[3]}]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[2]}]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[1]}]
set_input_delay -clock clk  230.7  [get_ports {wr_addr[0]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[15]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[14]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[13]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[12]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[11]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[10]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[9]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[8]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[7]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[6]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[5]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[4]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[3]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[2]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[1]}]
set_input_delay -clock clk  230.7  [get_ports {wr_data[0]}]
set_input_delay -clock clk  230.7  [get_ports rd_en]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[5]}]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[4]}]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[3]}]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[2]}]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[1]}]
set_input_delay -clock clk  230.7  [get_ports {rd_addr[0]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[15]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[14]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[13]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[12]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[11]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[10]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[9]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[8]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[7]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[6]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[5]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[4]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[3]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[2]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[1]}]
set_output_delay -clock clk  230.7  [get_ports {rd_data[0]}]
