# Fugue MQ logic die (fugue2 base + mq_diff_decoder + mq_score_store).
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fugue_pkg.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_tlb_pkg.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp16_mult.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp16_add.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/dbuf_16x256.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_add.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_mul.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_exp.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_recip.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/gemv_unit.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/accumulator.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/softmax_unit.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_seg_tlb.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_ptw.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_scan_planner.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_tlb_top.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/mq_diff_decoder.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/attacc_controller.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fugue_mq_logic_die.sv
