# Fugue logic die (with TLB + rotate-Q + diff_decoder) — full filelist.
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fugue_pkg.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_tlb_pkg.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp16_mult.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp16_add.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/dbuf_16x256.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_add.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_mul.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_exp.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fp32_recip.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/gemv_unit.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/bf16_mult.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/bf16_add.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/sincos_bf16.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/rotate_q_bf16.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/accumulator.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/softmax_unit.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_seg_tlb.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_ptw.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_scan_planner.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/kv_tlb_top.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/diff_decoder.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/attacc_controller.sv
/data2/chenyi9/KV-PIM/fugue-logic-die-rtl/rtl/fugue_logic_die.sv
