###################################################################

# Created by write_sdc on Mon Aug 31 00:32:21 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports sub_valid]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[31\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[30\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[29\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[28\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[27\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[26\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[25\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[24\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[23\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[22\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[21\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[20\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[19\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[18\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[17\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[16\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[15\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[14\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[13\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[12\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[11\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[10\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[9\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[8\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[7\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[6\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[5\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[4\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[3\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[2\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[1\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {score\\\\[0\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[31\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[30\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[29\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[28\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[27\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[26\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[25\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[24\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[23\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[22\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[21\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[20\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[19\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[18\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[17\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[16\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[15\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[14\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[13\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[12\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[11\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[10\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[9\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[8\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[7\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[6\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[5\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[4\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[3\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[2\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[1\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {neg_max\\\\[0\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports norm_valid]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[31\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[30\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[29\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[28\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[27\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[26\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[25\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[24\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[23\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[22\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[21\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[20\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[19\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[18\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[17\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[16\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[15\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[14\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[13\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[12\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[11\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[10\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[9\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[8\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[7\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[6\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[5\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[4\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[3\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[2\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[1\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {norm_exp\\\\[0\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[31\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[30\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[29\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[28\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[27\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[26\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[25\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[24\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[23\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[22\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[21\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[20\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[19\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[18\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[17\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[16\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[15\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[14\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[13\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[12\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[11\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[10\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[9\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[8\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[7\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[6\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[5\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[4\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[3\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[2\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[1\\\\]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports                        \
{reciprocal\\\\[0\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[31\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[30\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[29\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[28\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[27\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[26\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[25\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[24\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[23\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[22\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[21\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[20\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[19\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[18\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[17\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[16\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[15\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[14\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[13\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[12\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[11\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[10\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[9\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[8\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[7\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[6\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[5\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[4\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[3\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[2\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[1\\\\]}]
set_load -pin_load 0.005 [get_ports {exp_y\\\\[0\\\\]}]
set_load -pin_load 0.005 [get_ports sub_done]
set_load -pin_load 0.005 [get_ports exp_done]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[31\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[30\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[29\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[28\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[27\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[26\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[25\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[24\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[23\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[22\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[21\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[20\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[19\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[18\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[17\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[16\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[15\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[14\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[13\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[12\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[11\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[10\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[9\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[8\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[7\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[6\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[5\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[4\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[3\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[2\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[1\\\\]}]
set_load -pin_load 0.005 [get_ports {prob_y\\\\[0\\\\]}]
set_load -pin_load 0.005 [get_ports norm_done]
create_clock [get_ports clk]  -period 699  -waveform {0 349.5}
set_clock_uncertainty 50  [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports sub_valid]
set_input_delay -clock clk  0  [get_ports {score\\\\[31\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[30\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[29\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[28\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[27\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[26\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[25\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[24\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[23\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[22\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[21\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[20\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[19\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[18\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[17\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[16\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[15\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[14\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[13\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[12\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[11\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[10\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[9\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[8\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[7\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[6\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[5\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[4\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[3\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[2\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[1\\\\]}]
set_input_delay -clock clk  0  [get_ports {score\\\\[0\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[31\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[30\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[29\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[28\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[27\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[26\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[25\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[24\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[23\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[22\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[21\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[20\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[19\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[18\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[17\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[16\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[15\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[14\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[13\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[12\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[11\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[10\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[9\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[8\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[7\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[6\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[5\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[4\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[3\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[2\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[1\\\\]}]
set_input_delay -clock clk  0  [get_ports {neg_max\\\\[0\\\\]}]
set_input_delay -clock clk  0  [get_ports norm_valid]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[31\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[30\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[29\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[28\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[27\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[26\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[25\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[24\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[23\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[22\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[21\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[20\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[19\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[18\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[17\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[16\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[15\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[14\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[13\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[12\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[11\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[10\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[9\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[8\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[7\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[6\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[5\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[4\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[3\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[2\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[1\\\\]}]
set_input_delay -clock clk  0  [get_ports {norm_exp\\\\[0\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[31\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[30\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[29\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[28\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[27\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[26\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[25\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[24\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[23\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[22\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[21\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[20\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[19\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[18\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[17\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[16\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[15\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[14\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[13\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[12\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[11\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[10\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[9\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[8\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[7\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[6\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[5\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[4\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[3\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[2\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[1\\\\]}]
set_input_delay -clock clk  0  [get_ports {reciprocal\\\\[0\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[31\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[30\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[29\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[28\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[27\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[26\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[25\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[24\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[23\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[22\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[21\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[20\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[19\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[18\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[17\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[16\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[15\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[14\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[13\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[12\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[11\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[10\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[9\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[8\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[7\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[6\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[5\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[4\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[3\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[2\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[1\\\\]}]
set_output_delay -clock clk  0  [get_ports {exp_y\\\\[0\\\\]}]
set_output_delay -clock clk  0  [get_ports sub_done]
set_output_delay -clock clk  0  [get_ports exp_done]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[31\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[30\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[29\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[28\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[27\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[26\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[25\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[24\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[23\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[22\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[21\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[20\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[19\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[18\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[17\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[16\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[15\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[14\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[13\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[12\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[11\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[10\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[9\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[8\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[7\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[6\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[5\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[4\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[3\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[2\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[1\\\\]}]
set_output_delay -clock clk  0  [get_ports {prob_y\\\\[0\\\\]}]
set_output_delay -clock clk  0  [get_ports norm_done]
