###################################################################

# Created by write_sdc on Tue Sep  1 00:39:10 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports in_valid]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[31]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[30]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[29]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[28]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[27]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[26]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[25]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[24]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[23]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[22]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[21]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[20]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[19]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[18]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[17]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[16]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[15]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[14]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[13]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[12]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[11]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[10]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[9]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[8]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[7]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[6]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {a[0]}]
set_load -pin_load 0.005 [get_ports {y[31]}]
set_load -pin_load 0.005 [get_ports {y[30]}]
set_load -pin_load 0.005 [get_ports {y[29]}]
set_load -pin_load 0.005 [get_ports {y[28]}]
set_load -pin_load 0.005 [get_ports {y[27]}]
set_load -pin_load 0.005 [get_ports {y[26]}]
set_load -pin_load 0.005 [get_ports {y[25]}]
set_load -pin_load 0.005 [get_ports {y[24]}]
set_load -pin_load 0.005 [get_ports {y[23]}]
set_load -pin_load 0.005 [get_ports {y[22]}]
set_load -pin_load 0.005 [get_ports {y[21]}]
set_load -pin_load 0.005 [get_ports {y[20]}]
set_load -pin_load 0.005 [get_ports {y[19]}]
set_load -pin_load 0.005 [get_ports {y[18]}]
set_load -pin_load 0.005 [get_ports {y[17]}]
set_load -pin_load 0.005 [get_ports {y[16]}]
set_load -pin_load 0.005 [get_ports {y[15]}]
set_load -pin_load 0.005 [get_ports {y[14]}]
set_load -pin_load 0.005 [get_ports {y[13]}]
set_load -pin_load 0.005 [get_ports {y[12]}]
set_load -pin_load 0.005 [get_ports {y[11]}]
set_load -pin_load 0.005 [get_ports {y[10]}]
set_load -pin_load 0.005 [get_ports {y[9]}]
set_load -pin_load 0.005 [get_ports {y[8]}]
set_load -pin_load 0.005 [get_ports {y[7]}]
set_load -pin_load 0.005 [get_ports {y[6]}]
set_load -pin_load 0.005 [get_ports {y[5]}]
set_load -pin_load 0.005 [get_ports {y[4]}]
set_load -pin_load 0.005 [get_ports {y[3]}]
set_load -pin_load 0.005 [get_ports {y[2]}]
set_load -pin_load 0.005 [get_ports {y[1]}]
set_load -pin_load 0.005 [get_ports {y[0]}]
set_load -pin_load 0.005 [get_ports out_valid]
create_clock [get_ports clk]  -period 699  -waveform {0 349.5}
set_clock_uncertainty 50  [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  209.7  [get_ports in_valid]
set_input_delay -clock clk  209.7  [get_ports {a[31]}]
set_input_delay -clock clk  209.7  [get_ports {a[30]}]
set_input_delay -clock clk  209.7  [get_ports {a[29]}]
set_input_delay -clock clk  209.7  [get_ports {a[28]}]
set_input_delay -clock clk  209.7  [get_ports {a[27]}]
set_input_delay -clock clk  209.7  [get_ports {a[26]}]
set_input_delay -clock clk  209.7  [get_ports {a[25]}]
set_input_delay -clock clk  209.7  [get_ports {a[24]}]
set_input_delay -clock clk  209.7  [get_ports {a[23]}]
set_input_delay -clock clk  209.7  [get_ports {a[22]}]
set_input_delay -clock clk  209.7  [get_ports {a[21]}]
set_input_delay -clock clk  209.7  [get_ports {a[20]}]
set_input_delay -clock clk  209.7  [get_ports {a[19]}]
set_input_delay -clock clk  209.7  [get_ports {a[18]}]
set_input_delay -clock clk  209.7  [get_ports {a[17]}]
set_input_delay -clock clk  209.7  [get_ports {a[16]}]
set_input_delay -clock clk  209.7  [get_ports {a[15]}]
set_input_delay -clock clk  209.7  [get_ports {a[14]}]
set_input_delay -clock clk  209.7  [get_ports {a[13]}]
set_input_delay -clock clk  209.7  [get_ports {a[12]}]
set_input_delay -clock clk  209.7  [get_ports {a[11]}]
set_input_delay -clock clk  209.7  [get_ports {a[10]}]
set_input_delay -clock clk  209.7  [get_ports {a[9]}]
set_input_delay -clock clk  209.7  [get_ports {a[8]}]
set_input_delay -clock clk  209.7  [get_ports {a[7]}]
set_input_delay -clock clk  209.7  [get_ports {a[6]}]
set_input_delay -clock clk  209.7  [get_ports {a[5]}]
set_input_delay -clock clk  209.7  [get_ports {a[4]}]
set_input_delay -clock clk  209.7  [get_ports {a[3]}]
set_input_delay -clock clk  209.7  [get_ports {a[2]}]
set_input_delay -clock clk  209.7  [get_ports {a[1]}]
set_input_delay -clock clk  209.7  [get_ports {a[0]}]
set_output_delay -clock clk  209.7  [get_ports {y[31]}]
set_output_delay -clock clk  209.7  [get_ports {y[30]}]
set_output_delay -clock clk  209.7  [get_ports {y[29]}]
set_output_delay -clock clk  209.7  [get_ports {y[28]}]
set_output_delay -clock clk  209.7  [get_ports {y[27]}]
set_output_delay -clock clk  209.7  [get_ports {y[26]}]
set_output_delay -clock clk  209.7  [get_ports {y[25]}]
set_output_delay -clock clk  209.7  [get_ports {y[24]}]
set_output_delay -clock clk  209.7  [get_ports {y[23]}]
set_output_delay -clock clk  209.7  [get_ports {y[22]}]
set_output_delay -clock clk  209.7  [get_ports {y[21]}]
set_output_delay -clock clk  209.7  [get_ports {y[20]}]
set_output_delay -clock clk  209.7  [get_ports {y[19]}]
set_output_delay -clock clk  209.7  [get_ports {y[18]}]
set_output_delay -clock clk  209.7  [get_ports {y[17]}]
set_output_delay -clock clk  209.7  [get_ports {y[16]}]
set_output_delay -clock clk  209.7  [get_ports {y[15]}]
set_output_delay -clock clk  209.7  [get_ports {y[14]}]
set_output_delay -clock clk  209.7  [get_ports {y[13]}]
set_output_delay -clock clk  209.7  [get_ports {y[12]}]
set_output_delay -clock clk  209.7  [get_ports {y[11]}]
set_output_delay -clock clk  209.7  [get_ports {y[10]}]
set_output_delay -clock clk  209.7  [get_ports {y[9]}]
set_output_delay -clock clk  209.7  [get_ports {y[8]}]
set_output_delay -clock clk  209.7  [get_ports {y[7]}]
set_output_delay -clock clk  209.7  [get_ports {y[6]}]
set_output_delay -clock clk  209.7  [get_ports {y[5]}]
set_output_delay -clock clk  209.7  [get_ports {y[4]}]
set_output_delay -clock clk  209.7  [get_ports {y[3]}]
set_output_delay -clock clk  209.7  [get_ports {y[2]}]
set_output_delay -clock clk  209.7  [get_ports {y[1]}]
set_output_delay -clock clk  209.7  [get_ports {y[0]}]
set_output_delay -clock clk  209.7  [get_ports out_valid]
