###################################################################

# Created by write_sdc on Tue Sep  1 00:26:27 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports in_valid]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[15]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[14]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[13]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[12]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[11]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[10]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[9]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[8]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[7]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[6]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {q_pos[0]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[15]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[14]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[13]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[12]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[11]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[10]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[9]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[8]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[7]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[6]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[5]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[4]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[3]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[2]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[1]}]
set_driving_cell -lib_cell BUFx2_ASAP7_75t_R [get_ports {word_base[0]}]
set_load -pin_load 0.005 [get_ports {keep_mask[15]}]
set_load -pin_load 0.005 [get_ports {keep_mask[14]}]
set_load -pin_load 0.005 [get_ports {keep_mask[13]}]
set_load -pin_load 0.005 [get_ports {keep_mask[12]}]
set_load -pin_load 0.005 [get_ports {keep_mask[11]}]
set_load -pin_load 0.005 [get_ports {keep_mask[10]}]
set_load -pin_load 0.005 [get_ports {keep_mask[9]}]
set_load -pin_load 0.005 [get_ports {keep_mask[8]}]
set_load -pin_load 0.005 [get_ports {keep_mask[7]}]
set_load -pin_load 0.005 [get_ports {keep_mask[6]}]
set_load -pin_load 0.005 [get_ports {keep_mask[5]}]
set_load -pin_load 0.005 [get_ports {keep_mask[4]}]
set_load -pin_load 0.005 [get_ports {keep_mask[3]}]
set_load -pin_load 0.005 [get_ports {keep_mask[2]}]
set_load -pin_load 0.005 [get_ports {keep_mask[1]}]
set_load -pin_load 0.005 [get_ports {keep_mask[0]}]
set_load -pin_load 0.005 [get_ports out_valid]
create_clock [get_ports clk]  -period 1501.5  -waveform {0 750.751}
set_clock_uncertainty 50  [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_false_path   -from [get_ports rst_n]
set_input_delay -clock clk  450.45  [get_ports in_valid]
set_input_delay -clock clk  450.45  [get_ports {q_pos[15]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[14]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[13]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[12]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[11]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[10]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[9]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[8]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[7]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[6]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[5]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[4]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[3]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[2]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[1]}]
set_input_delay -clock clk  450.45  [get_ports {q_pos[0]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[15]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[14]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[13]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[12]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[11]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[10]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[9]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[8]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[7]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[6]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[5]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[4]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[3]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[2]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[1]}]
set_input_delay -clock clk  450.45  [get_ports {word_base[0]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[15]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[14]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[13]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[12]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[11]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[10]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[9]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[8]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[7]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[6]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[5]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[4]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[3]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[2]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[1]}]
set_output_delay -clock clk  450.45  [get_ports {keep_mask[0]}]
set_output_delay -clock clk  450.45  [get_ports out_valid]
